<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <PackageId>TwitchLib.EventSub.Webhooks</PackageId>
    <Authors>swiftyspiffy, Prom3theu5, Syzuna, LuckyNoS7evin</Authors>
    <PackageTags>twitchlib;twitch,eventsub;webhooks</PackageTags>
    <VersionPrefix>3.1.0</VersionPrefix>
    <VersionSuffix>$(VersionSuffix)</VersionSuffix>
    <FileVersion>$(VersionSuffix)</FileVersion>
    <AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
    <PackageReleaseNotes>
	</PackageReleaseNotes>
    <RepositoryType>git</RepositoryType>
	<PackageIcon>twitchlib.png</PackageIcon>
    <PackageProjectUrl>https://github.com/TwitchLib/TwitchLib.EventSub.Webhooks</PackageProjectUrl>
    <RepositoryUrl>https://github.com/TwitchLib/TwitchLib.EventSub.Webhooks</RepositoryUrl>
    <NeutralLanguage>en-US</NeutralLanguage>
	<PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <Copyright>Copyright $([System.DateTimeOffset]::Now.Year)</Copyright>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
	<Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TwitchLib.EventSub.Core" Version="3.1.0-preview.81.5919dce" />
  </ItemGroup>

  <ItemGroup>
	<None Include="..\README.md" Pack="true" PackagePath="\" />
	<None Include="..\twitchlib.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
